### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by godartm** [leohajder/leohajder.github.io#2]
Hello man maybe you can modify your img to WebP ?.
WebP lossless images are 26% smaller in size compared to PNGs. WebP lossy images are 25-34% smaller than comparable JPEG images at equivalent SSIM quality index.

**Comment by leohajder** [comment]
Hey, thanks for the comment. I'll look into it. Can you tell me more, since you already took the time to hit me up? I'd like to know if WebP preserves transparency, for example...

**Comment by godartm** [comment]
Yes Webp preserves transparency.
I have an other tip for you dont work on your master. Create other branch and allow people to commit and merge request can be good. For example  : translation to french.

**Comment by leohajder** [comment]
Yeah, I don't see people committing to this, this is just a one pager portfolio. I didn't even make a version in Croatian because I don't need it. We'll see about other projects. What about you? What do you do? I'm going to follow you, I'm expecting good stuff. :)

**Comment by godartm** [comment]
Actually i work on private project. but i will soon create open source project.;)

**Comment by leohajder** [comment]
gimp 2.8.16 doesn't support webp yet, but it's announced for 2.9 dev and 2.10 release. i'll revisit this then. i'll close this issue now.
